name: Scheduler Workflow 

on:
  schedule:
    - cron: '*/260 11-23 * * *'
    - cron: '*/260 0-4 * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add dot to text file
        run: |
          echo "." >> pared.txt
                
      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pytz PyExecJS

      - name: Run script
        run: python output/estadisticas.py

      - name: Run script 2
        run: python output/estadisticas_eur.py

      # - name: Run script 3
      #   run: python output/estadisticas_payp.py

      # - name: Run script 4
      #   run: python output/estadisticas_paralelo.py

      - name: Run script 5
        run: python output/estadisticas_fecha.py

      # Runs a single command using the runners shell
      - name: Commit changes
        run: |
          git config --global user.email "solartech4756@gmail.com"
          git config --global user.name "solarapptech"
          git add pared.txt
          git add output/outputBcv.js
          git add output/outputBcv_eur.js
          # git add output/outputPayp.js
          # git add output/outputParalelo.js
          git add output/outputFecha.js
          git commit -m "Automated commit"

      - name: Push changes
        run: |
          git push origin main
