name: Scheduler Workflow 

on:
  schedule:
    - cron: '*/55 11-23 * * *'
    - cron: '*/55 0-4 * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add dot to text file
        run: |
          echo "." >> pared.txt

      # Runs a single command using the runners shell
      - name: Commit changes
        run: |
          git config --global user.email "solartech4756@gmail.com"
          git config --global user.name "solarapptech"
          git add pared.txt
          git commit -m "Automated commit"

      - name: Push changes
        run: |
          git push origin main

  append_numbers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run script
        run: estadisticas.py

      - name: Upload output.txt
        uses: actions/upload-artifact@v3
        with:
          name: output-file
          path: output.txt
