name: Sample Scheduler Workflow (Every 5 min)

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  schedule:
    - cron: '*/5 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add dot to text file
        run: |
          echo "." >> pared.txt

      # Runs a single command using the runners shell
      - name: Commit changes
        run: |
          git config --global user.email "solartech4756@gmail.com"
          git config --global user.name "solarapptech"
          git add pared.txt
          git commit -m "Automated commit"

      - name: Push changes
        run: |
          git push origin main
